# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alltimeranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField(blank=True, null=True)),
                ('uid', models.TextField(blank=True, null=True)),
                ('birthday', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('song', models.TextField(blank=True, null=True)),
                ('singer', models.TextField(blank=True, null=True)),
                ('addedtime', models.TextField(blank=True, db_column='addedTime', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lastweekranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField(blank=True, null=True)),
                ('uid', models.TextField(blank=True, null=True)),
                ('birthday', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('song', models.TextField(blank=True, null=True)),
                ('singer', models.TextField(blank=True, null=True)),
                ('addedtime', models.TextField(blank=True, db_column='addedTime', null=True)),
            ],
        ),
    ]
